# Generated by Django 5.2.8 on 2025-11-16 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basura', '0001_initial'),
        ('juarez_mueve', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadbasura',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_basura_que_conduce', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonabasura',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zonas_basura', to='juarez_mueve.empresa'),
        ),
    ]
