# Generated by Django 5.2.8 on 2025-11-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basura', '0002_unidadbasura_conductor_zonabasura_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_unidad', models.CharField(max_length=20, unique=True)),
                ('zona', models.CharField(blank=True, max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('FUERA_SERV', 'Fuera de servicio')], default='ACTIVO', max_length=20)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='unidadbasura',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='zonabasura',
            name='empresa',
        ),
    ]
