# Generated by Django 5.2.8 on 2025-11-17 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basura', '0003_unidadrecoleccion_remove_unidadbasura_conductor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='basura.unidadbasura')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
