# Generated by Django 5.2.8 on 2025-11-17 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basura', '0004_puntoruta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PuntoRuta',
        ),
    ]
