# Generated by Django 5.2.8 on 2025-11-16 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('TRANSPORTE', 'Transporte'), ('BASURA', 'Recolección de basura'), ('MIXTA', 'Mixta')], default='MIXTA', max_length=15)),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro'), ('Prefiero no decir', 'Prefiero no decir')], max_length=20, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('rol', models.CharField(choices=[('CIUDADANO', 'Ciudadano'), ('CONDUCTOR', 'Conductor'), ('COORDINADOR', 'Coordinador de empresa'), ('EMPRESA_ADMIN', 'Administrador de empresa'), ('APP_ADMIN', 'Administrador general')], default='CIUDADANO', max_length=20)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='juarez_mueve.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
