# Generated by Django 5.2.8 on 2025-11-16 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juarez_mueve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(choices=[('universidad', 'Universidad'), ('gobierno', 'Gobierno'), ('maquiladora', 'Maquiladora'), ('privado', 'Privado'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='juarez_mueve.empresa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('admin_app', 'Administrador de la Aplicación'), ('admin_empresa', 'Administrador de Empresa / Coordinador'), ('conductor', 'Conductor de Transporte'), ('recolector', 'Conductor de Recolección de Basura'), ('usuario', 'Usuario Normal')], default='usuario', max_length=30),
        ),
    ]
