# Generated by Django 5.2.8 on 2025-11-16 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juarez_mueve', '0002_empresa_direccion_empresa_sitio_web_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juarez_mueve.empresa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('APP_ADMIN', 'Administrador General'), ('EMPRESA_ADMIN', 'Administrador de Empresa'), ('COORDINADOR_TRANSPORTE', 'Coordinador de Transporte'), ('COORDINADOR_BASURA', 'Coordinador de Basura'), ('CONDUCTOR', 'Conductor de Transporte'), ('RECOLECTOR', 'Personal de Basura'), ('CIUDADANO', 'Ciudadano')], default='CIUDADANO', max_length=40),
        ),
    ]
