# Generated by Django 5.2.8 on 2025-11-16 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juarez_mueve', '0003_alter_profile_empresa_alter_profile_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jm_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
