# Generated by Django 5.2.8 on 2025-11-16 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juarez_mueve', '0005_alter_profile_user_conductor_ruta_camion_unidad'),
        ('transporte', '0005_ruta_color_ruta_destino_ruta_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ruta_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.ruta'),
        ),
    ]
