# Generated by Django 5.2.8 on 2025-11-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juarez_mueve', '0006_profile_ruta_asignada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ruta_asignada',
        ),
        migrations.DeleteModel(
            name='Camion',
        ),
        migrations.DeleteModel(
            name='Conductor',
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
