# Generated by Django 5.2.8 on 2025-11-05 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RutaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_ruta', models.CharField(max_length=20, unique=True)),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('colonias', models.TextField(help_text='Lista de colonias que cubre la ruta')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='transporte.rutatransporte')),
            ],
        ),
    ]
