# Generated by Django 5.2.8 on 2025-11-05 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='unidadtransporte',
            name='ruta',
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('transporte', 'Transporte Público'), ('basura', 'Recolección de Basura')], max_length=15)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionTiempoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='transporte.unidad')),
            ],
        ),
        migrations.DeleteModel(
            name='RutaTransporte',
        ),
        migrations.DeleteModel(
            name='UnidadTransporte',
        ),
    ]
