# Generated by Django 5.2.8 on 2025-11-16 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juarez_mueve', '0001_initial'),
        ('transporte', '0002_ruta_remove_unidadtransporte_ruta_unidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutas_transporte', to='juarez_mueve.empresa'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_que_conduce', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidad',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='juarez_mueve.empresa'),
        ),
    ]
