# Generated by Django 5.2.8 on 2025-11-16 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_ruta_empresa_unidad_activo_unidad_conductor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='empresa',
        ),
        migrations.CreateModel(
            name='PuntoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Orden del punto en la ruta')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='transporte.ruta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
