# Generated by Django 5.2.8 on 2025-11-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_remove_ruta_empresa_puntoruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='color',
            field=models.CharField(default='#2563eb', help_text='Color HEX de la ruta', max_length=7),
        ),
        migrations.AddField(
            model_name='ruta',
            name='destino',
            field=models.CharField(blank=True, help_text='Dirección o lugar de llegada', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='origen',
            field=models.CharField(blank=True, help_text='Dirección o lugar de partida', max_length=255, null=True),
        ),
    ]
