# Generated by Django 5.2.8 on 2025-11-16 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juarez_mueve', '0007_remove_conductor_empresa_remove_ruta_empresa_and_more'),
        ('transporte', '0005_ruta_color_ruta_destino_ruta_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('transporte', 'Transporte público'), ('basura', 'Recolección de basura')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juarez_mueve.empresa')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.ruta')),
            ],
        ),
    ]
