# Generated by Django 5.2.8 on 2025-11-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0006_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='destino_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='destino_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='origen_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='origen_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='color',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
