# Generated by Django 5.2.8 on 2025-11-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='ruta',
        ),
        migrations.DeleteModel(
            name='Camion',
        ),
        migrations.DeleteModel(
            name='Conductor',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
